{"stop": 1594457558488, "uuid": "983d6e52-b51d-49f2-9f68-db14b898883d", "status": "broken", "fullName": "webtest.testcases.test_loginpytest.TestLogin#test_login_1", "labels": [{"value": "登录用例", "name": "feature"}, {"value": "账户、密码未输入用例", "name": "story"}, {"value": "@pytest.mark.usefixtures('init_driver', 'setup')", "name": "tag"}, {"value": "run(order=1)", "name": "tag"}, {"value": "demo", "name": "tag"}, {"value": "webtest.testcases", "name": "parentSuite"}, {"value": "test_loginpytest", "name": "suite"}, {"value": "TestLogin", "name": "subSuite"}, {"value": "cnki-PC", "name": "host"}, {"value": "900832-MainThread", "name": "thread"}, {"value": "pytest", "name": "framework"}, {"value": "cpython3", "name": "language"}, {"value": "webtest.testcases.test_loginpytest", "name": "package"}], "start": 1594457558485, "parameters": [{"value": "{'pwd': '', 'expected': '请输入密码', 'phone': '18684720553'}", "name": "data"}], "attachments": [{"source": "729b3e4c-6f2c-4373-8a88-192ce1a16fac-attachment.attach"}], "testCaseId": "3d70387b5c8f3b77523cb541df7f68db", "historyId": "418e129d1f1291295228205c104bda2b", "name": "test_login_1[请输入密码]", "statusDetails": {"message": "AttributeError: __exit__", "trace": "self = <webtest.testcases.test_loginpytest.TestLogin object at 0x000000000461B4E0>\ndata = {'expected': '请输入密码', 'phone': '18684720553', 'pwd': ''}\ninit_driver = (<selenium.webdriver.chrome.webdriver.WebDriver (session=\"369d12f3acf4705f9d314ba35e0a0e50\")>, <webtest.pages.loginpage.LoginPage object at 0x00000000044CCC50>, <webtest.pages.indexpage.IndexPage object at 0x00000000044CCF28>)\n\n    @allure.story('账户、密码未输入用例')\n    @pytest.mark.run(order=1)\n    @pytest.mark.demo\n    @pytest.mark.usefixtures('init_driver','setup')  #单独使用 usefixtures 不能使用 fixture 的返回值，若使用返回值需要将fixture函数作为参数放到测试函数中。\n    @pytest.mark.parametrize(\"data\",data_login.incorrect_data1,ids=idfn)  #将idfn赋值给ids设置子用例名称\n    def test_login_1(self,data,init_driver):  # 使用返回值需要将fixture函数init_driver作为参数放到测试函数中\n        # print(data)\n>       with allure.attach('输入用户名、密码'):\nE       AttributeError: __exit__\n\ntest_loginpytest.py:32: AttributeError"}}