{"stop": 1594457558075, "uuid": "9348d288-9ec9-4f5d-9bff-e3b864ca3ddd", "status": "broken", "fullName": "webtest.testcases.test_loginpytest.TestLogin#test_login_1", "labels": [{"value": "登录用例", "name": "feature"}, {"value": "账户、密码未输入用例", "name": "story"}, {"value": "@pytest.mark.usefixtures('init_driver', 'setup')", "name": "tag"}, {"value": "run(order=1)", "name": "tag"}, {"value": "demo", "name": "tag"}, {"value": "webtest.testcases", "name": "parentSuite"}, {"value": "test_loginpytest", "name": "suite"}, {"value": "TestLogin", "name": "subSuite"}, {"value": "cnki-PC", "name": "host"}, {"value": "900832-MainThread", "name": "thread"}, {"value": "pytest", "name": "framework"}, {"value": "cpython3", "name": "language"}, {"value": "webtest.testcases.test_loginpytest", "name": "package"}], "start": 1594457558073, "parameters": [{"value": "{'pwd': 'python', 'expected': '请输入手机号', 'phone': ''}", "name": "data"}], "attachments": [{"source": "3e1008b1-9a34-45ca-8c58-cbd27d3c1ae1-attachment.attach"}], "testCaseId": "3d70387b5c8f3b77523cb541df7f68db", "historyId": "8f865ae828fd13b6208ee505f922bc68", "name": "test_login_1[请输入手机号]", "statusDetails": {"message": "AttributeError: __exit__", "trace": "self = <webtest.testcases.test_loginpytest.TestLogin object at 0x00000000044CC828>\ndata = {'expected': '请输入手机号', 'phone': '', 'pwd': 'python'}\ninit_driver = (<selenium.webdriver.chrome.webdriver.WebDriver (session=\"369d12f3acf4705f9d314ba35e0a0e50\")>, <webtest.pages.loginpage.LoginPage object at 0x00000000044CCC50>, <webtest.pages.indexpage.IndexPage object at 0x00000000044CCF28>)\n\n    @allure.story('账户、密码未输入用例')\n    @pytest.mark.run(order=1)\n    @pytest.mark.demo\n    @pytest.mark.usefixtures('init_driver','setup')  #单独使用 usefixtures 不能使用 fixture 的返回值，若使用返回值需要将fixture函数作为参数放到测试函数中。\n    @pytest.mark.parametrize(\"data\",data_login.incorrect_data1,ids=idfn)  #将idfn赋值给ids设置子用例名称\n    def test_login_1(self,data,init_driver):  # 使用返回值需要将fixture函数init_driver作为参数放到测试函数中\n        # print(data)\n>       with allure.attach('输入用户名、密码'):\nE       AttributeError: __exit__\n\ntest_loginpytest.py:32: AttributeError"}}